[[manager.prepend_keymap]]
on = "<C-p>"
run = '''
  shell 'qlmanage -p "$@"' --confirm
'''

[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"


[[manager.prepend_keymap]]
on = "p"
run = "plugin --sync smart-paste"
desc = "Paste into the hovered directory or CWD (smart-paste)"


[[manager.prepend_keymap]]
on = "l"
run = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file (smart-enter)"

[[manager.prepend_keymap]]
on = "<C-d>"
run = "shell 'ripdrag -x \"$@\"' --confirm"
desc = "Drag and drop selected files"

[[manager.prepend_keymap]]
on = "<C-y>"
run = "shell --confirm 'impbcopy \"$0\"'"
desc = "Copy image to clipboard (for pasting into apps)"
